apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend-dev-deployment
  labels:
    app: backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend-dev
        image: miguelmcell/ethical_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: backend-dev-nodeport
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
          app: backend-dev
